version: 1
directus: 11.3.5
vendor: postgres
collections:
  - collection: nodes
    meta:
      accountability: all
      archive_app_filter: true
      archive_field: null
      archive_value: null
      collapse: open
      collection: nodes
      color: null
      display_template: null
      group: null
      hidden: false
      icon: null
      item_duplication_fields: null
      note: null
      preview_url: null
      singleton: false
      sort: null
      sort_field: null
      translations: null
      unarchive_value: null
      versioning: false
    schema:
      name: nodes
fields:
  - collection: nodes
    field: id
    type: integer
    meta:
      collection: nodes
      conditions: null
      display: null
      display_options: null
      field: id
      group: null
      hidden: true
      interface: input
      note: null
      options: null
      readonly: true
      required: false
      sort: 1
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      name: id
      table: nodes
      data_type: integer
      default_value: nextval('nodes_id_seq'::regclass)
      max_length: null
      numeric_precision: 32
      numeric_scale: 0
      is_nullable: false
      is_unique: true
      is_indexed: false
      is_primary_key: true
      is_generated: false
      generation_expression: null
      has_auto_increment: true
      foreign_key_table: null
      foreign_key_column: null
  - collection: nodes
    field: user_created
    type: uuid
    meta:
      collection: nodes
      conditions: null
      display: user
      display_options: null
      field: user_created
      group: null
      hidden: true
      interface: select-dropdown-m2o
      note: null
      options:
        template: '{{avatar}} {{first_name}} {{last_name}}'
      readonly: true
      required: false
      sort: 2
      special:
        - user-created
      translations: null
      validation: null
      validation_message: null
      width: half
    schema:
      name: user_created
      table: nodes
      data_type: uuid
      default_value: null
      max_length: null
      numeric_precision: null
      numeric_scale: null
      is_nullable: true
      is_unique: false
      is_indexed: false
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: directus_users
      foreign_key_column: id
  - collection: nodes
    field: date_created
    type: timestamp
    meta:
      collection: nodes
      conditions: null
      display: datetime
      display_options:
        relative: true
      field: date_created
      group: null
      hidden: true
      interface: datetime
      note: null
      options: null
      readonly: true
      required: false
      sort: 3
      special:
        - date-created
      translations: null
      validation: null
      validation_message: null
      width: half
    schema:
      name: date_created
      table: nodes
      data_type: timestamp with time zone
      default_value: null
      max_length: null
      numeric_precision: null
      numeric_scale: null
      is_nullable: true
      is_unique: false
      is_indexed: false
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: null
      foreign_key_column: null
  - collection: nodes
    field: user_updated
    type: uuid
    meta:
      collection: nodes
      conditions: null
      display: user
      display_options: null
      field: user_updated
      group: null
      hidden: true
      interface: select-dropdown-m2o
      note: null
      options:
        template: '{{avatar}} {{first_name}} {{last_name}}'
      readonly: true
      required: false
      sort: 4
      special:
        - user-updated
      translations: null
      validation: null
      validation_message: null
      width: half
    schema:
      name: user_updated
      table: nodes
      data_type: uuid
      default_value: null
      max_length: null
      numeric_precision: null
      numeric_scale: null
      is_nullable: true
      is_unique: false
      is_indexed: false
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: directus_users
      foreign_key_column: id
  - collection: nodes
    field: date_updated
    type: timestamp
    meta:
      collection: nodes
      conditions: null
      display: datetime
      display_options:
        relative: true
      field: date_updated
      group: null
      hidden: true
      interface: datetime
      note: null
      options: null
      readonly: true
      required: false
      sort: 5
      special:
        - date-updated
      translations: null
      validation: null
      validation_message: null
      width: half
    schema:
      name: date_updated
      table: nodes
      data_type: timestamp with time zone
      default_value: null
      max_length: null
      numeric_precision: null
      numeric_scale: null
      is_nullable: true
      is_unique: false
      is_indexed: false
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: null
      foreign_key_column: null
  - collection: nodes
    field: name
    type: string
    meta:
      collection: nodes
      conditions: null
      display: null
      display_options: null
      field: name
      group: null
      hidden: false
      interface: input
      note: null
      options: null
      readonly: false
      required: false
      sort: 6
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      name: name
      table: nodes
      data_type: character varying
      default_value: null
      max_length: 255
      numeric_precision: null
      numeric_scale: null
      is_nullable: true
      is_unique: false
      is_indexed: false
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: null
      foreign_key_column: null
  - collection: nodes
    field: parent
    type: integer
    meta:
      collection: nodes
      conditions: null
      display: null
      display_options: null
      field: parent
      group: null
      hidden: false
      interface: select-dropdown-m2o
      note: null
      options: null
      readonly: false
      required: false
      sort: 7
      special:
        - m2o
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      name: parent
      table: nodes
      data_type: integer
      default_value: null
      max_length: null
      numeric_precision: 32
      numeric_scale: 0
      is_nullable: true
      is_unique: false
      is_indexed: false
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: nodes
      foreign_key_column: id
relations:
  - collection: nodes
    field: user_updated
    related_collection: directus_users
    meta:
      junction_field: null
      many_collection: nodes
      many_field: user_updated
      one_allowed_collections: null
      one_collection: directus_users
      one_collection_field: null
      one_deselect_action: nullify
      one_field: null
      sort_field: null
    schema:
      table: nodes
      column: user_updated
      foreign_key_table: directus_users
      foreign_key_column: id
      constraint_name: nodes_user_updated_foreign
      on_update: NO ACTION
      on_delete: NO ACTION
  - collection: nodes
    field: user_created
    related_collection: directus_users
    meta:
      junction_field: null
      many_collection: nodes
      many_field: user_created
      one_allowed_collections: null
      one_collection: directus_users
      one_collection_field: null
      one_deselect_action: nullify
      one_field: null
      sort_field: null
    schema:
      table: nodes
      column: user_created
      foreign_key_table: directus_users
      foreign_key_column: id
      constraint_name: nodes_user_created_foreign
      on_update: NO ACTION
      on_delete: NO ACTION
  - collection: nodes
    field: parent
    related_collection: nodes
    meta:
      junction_field: null
      many_collection: nodes
      many_field: parent
      one_allowed_collections: null
      one_collection: nodes
      one_collection_field: null
      one_deselect_action: nullify
      one_field: null
      sort_field: null
    schema:
      table: nodes
      column: parent
      foreign_key_table: nodes
      foreign_key_column: id
      constraint_name: nodes_parent_foreign
      on_update: CASCADE
      on_delete: CASCADE